### ISSUE TITLE
Refactor Genus detection with centroid

### ISSUE THREAD

**Issue by algeboy** [thetensor-space/TameGenus#11]
There is in the code now 3 or more places that the decide if a tensor has genus 2 or 1 over a centroid.  This has been switched to now have different states, on or off, and because we don't yet support `TensorOverCentroid` for anything but fields we have no third work around.  The problem is fixing these workarounds in every place.  This suggests we should factor out and make one place that detects genus and does it over the centroid and all other things call it.  So far the places I've found are
```
TGAutomorphism
Genus2Signature
Genus()
PseudoIsometrey
```

**Comment by joshmaglione** [comment]
Good point. This is a manageable task that can be finished in a day or so.

What do you mean by third option? Either you check the genus over the (residue field of the) centroid or you don't.

**Comment by joshmaglione** [comment]
Added a new "Refactor" project for TameGenus, and made a card for this issue. It can be found here: [Refactor](https://github.com/thetensor-space/TameGenus/projects/3).

**Comment by joshmaglione** [comment]
This has been addressed, and it is refactored in the `dev` branch. Will come to master soon.
