### ISSUE TITLE
TGIsIsomorphic

### ISSUE THREAD

**Issue by eobr007** [thetensor-space/TameGenus#18]
Hi Josh,
I believe I've pulled down your test branch code but am not certain.
TGIsIsomorphic claims that these isomorphic  groups are not. 
Best wishes.
Eamonn 

H:=PCGroup(\[ 14, -13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, -13, 13, 
108289499649292053, 978519575151302, 7000178499109084, 90023800913389619, 
11742234901739905, 285642795111887, 60342040469225064, 1254512275979708, 
1071160481678592, 30434913201466, 150692014603395725, 8731405442147407, 
1771757337427929, 79279237326791, 4111282834993, 347048276457504264, 
10713534871939920, 648486348456708, 114316503456294, 11751416783350, 
744071915936, 271376102534492599, 23484470344063477, 1451374243771123, 
100954837229841, 8405289595311, 1033091602893, 16218079787, 187875861209757638, 
21000543403638730, 1893349135232136, 56119057464884, 5755799566126, 
1328260884756, 83320398344, 13048412298501589, 501919112631323, 
3030138435633437, 51962722681011, 14732148802345, 404104448099, 78387685833, 
2287188647, 539804841, 122010003909055272, 15733217031760252, 3057275537774496, 
76765029733444, 19849103232024, 763455637024, 81027214362, 1544174740, 
611402914, 13197320, 372138521500994987, 48196431618345217, 1715638326561471, 
69617722653077, 21937383531403, 1624240535817, 70611017663, 9236627509, 
604948467, 397625, 371431 ])
;
 G:= PCGroup(\[ 14, -13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, -13, 13, 
92633186446984821, 142863857971060592, 8129239547352394, 174828830759220459, 
4215161246784505, 447764381526311, 146777936273629574, 9659744524013238, 
376353682759632, 120997337846886, 62625252840417545, 24538260117553747, 
648486345842277, 30286450223531, 6646573915861, 157541652071243810, 
8605954248552408, 418814101036274, 166278550383994, 9912759738216, 707175787940,
412282921355257687, 23685192308195621, 2223381798125523, 32068009302833, 
14709256607199, 723866911117, 20542900651, 158520273955431578, 
20548918984341406, 677437237123956, 133616738882768, 14183929375498, 
126501287172, 62642348588, 2994108496, 502308199870602589, 25341262173984143, 
1119419738606297, 176671635307491, 15874171811745, 1133242215639, 15542632653, 
5146144747, 100482573255882828, 46368406807428730, 1783463073089736, 
153520396195218, 9924923280338, 96689895382, 92920471738, 3545444010, 180360302,
5077208, 653952159142525163, 15077307536541457, 3661097363534559, 
260244203382125, 22896682859299, 1434489020409, 55203843335, 7427688013, 
513781755, 397625, 371431 ])
;
TGIsIsomorphic (G, H);

**Comment by joshmaglione** [comment]
Indeed, I get the same error as you. Interestingly, the code shows that their tensors are pseudo-isometric. Thanks for pointing this out.

**Comment by joshmaglione** [comment]
This boils down to an issue with the function `__IsPseudoSGAdjTens`. It doesn't seem to be symmetric. That is, apparently `__IsPseudoSGAdjTens(s, t)` is not equal to `__IsPseudoSGAdjTens(t, s)`.

**Comment by joshmaglione** [comment]
This issue is now fixed on `test`. This issue points to a bug in underlying code. I will make a detailed issue about this.
